### ISSUE TITLE
messages are assumed to be in UTF-8

### ISSUE THREAD

**Issue by Akuli** [ThePhilgrim/MantaTail#60]
Even though most of the world now uses UTF-8, I think the server still shouldn't crash if you use some different encoding.

To demonstrate this, I created a script that sends `hellö wörld` to the server with the latin-1 encoding instead of utf-8:

```python3
import socket
s = socket.socket()
s.connect(('localhost', 6667))
s.sendall("NICK x\r\n".encode("latin-1"))
s.sendall("USER x\r\n".encode("latin-1"))
s.sendall("JOIN #foo\r\n".encode("latin-1"))
s.sendall("PRIVMSG #foo :hellö world\r\n".encode("latin-1"))
```

This causes an error in mantatail:

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/akuli/MantaTail/mantatail.py", line 101, in recv_loop
    decoded_message = request.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 4: invalid start byte
```

IRC servers should pass the messages from one client to another as they are, without attempting to interpret the bytes with a given encoding. The text of a PRIVMSG is not a string, as far as a correctly working server is concerned; it is just some bytes that gets transferred from one client to another, and it is the client's responsibility to interpret it as text.

Implementing this in mantatail is going to be annoying, because f-strings don't work with bytes. So `f"PRIVMSG {receiver} :{privmsg}"` must change to something quite different:

```python3
# If privmsg is bytes and everything else is strings:
f"PRIVMSG {receiver} :".encode() + privmsg

# If everything is bytes, both of these will work:
b"PRIVMSG %s :%s" % (receiver, privmsg)
b"PRIVMSG " + receiver + b" :" + privmsg
```

**Comment by Akuli** [comment]
Here's a simpler fix that will work, even though it feels a bit weird: use latin-1 instead of UTF-8 in the server.

Latin-1 is an encoding consisting of only 256 different characters: ö is valid latin-1, but € isn't. It is super simple: every byte represents some character, so ö is 256, x is 120, and so on. Because there are 256 different bytes, this means that any byte is some valid latin-1 character.

A downside is that debugging the server might look weird, when someone sends text utf-8 encoded text:

```
>>> received_bytes = "hellö wörld".encode("utf-8")
>>> received_bytes.decode("latin-1")
'hellÃ¶ wÃ¶rld'
```
