### ISSUE TITLE
AttributeError: 'UserConnection' object has no attribute 'nick'

### ISSUE THREAD

**Issue by Akuli** [ThePhilgrim/MantaTail#69]
I don't know yet when and why this happens, but it can happen. Here's an error message, taken from https://github.com/Akuli/mantaray/runs/4889957324?check_suite_focus=true

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/work/mantaray/mantaray/mantatail/mantatail.py", line 173, in send_queue_thread
    self.queue_quit_message_for_other_users()
  File "/home/runner/work/mantaray/mantaray/mantatail/mantatail.py", line 208, in queue_quit_message_for_other_users
    if channel.is_operator(self):
  File "/home/runner/work/mantaray/mantaray/mantatail/mantatail.py", line 262, in is_operator
    return user.nick.lower() in self.operators
AttributeError: 'UserConnection' object has no attribute 'nick'
```

**Comment by Akuli** [comment]
This is the same bug as #77. The error message is the same.
